---
- name: "Add gcloud docker alias"
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK: gcloud docker alias"
    path: ~/.zshrc
    create: true
    block: |
      alias gcloud='docker run --rm -it --volume ${HOME}/.config/gcloud:/root/.config/gcloud --volume ${PWD}:/workdir --workdir="/workdir" google/cloud-sdk gcloud'

- name: "Install terraform switch"
  community.general.homebrew:
    name: warrensbox/tap/tfswitch
    state: present  