- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install extensions
  shell: code --install-extension {{ item }}
  register: code_install_extension
  changed_when:
    - 'code_install_extension.stdout is search("was successfully installed")'
  with_items: 
    - "{{ extensions }}"