---
- name: Create dotnet directory
  file:
    path: /usr/local/share/dotnet
    state: directory

- block:
  - name: "Install dotnet-sdk-3.1.416-osx-x64 : Determine whether SDK is installed"
    shell: dotnet --list-sdks | grep -q ^3\.1\.416\\s
    failed_when: false
    register: dotnet_3_1_416_sdk
    changed_when: false

  - name: "Install dotnet-sdk-3.1.416-osx-x64 : Install SDK"
    when: dotnet_3_1_416_sdk.rc != 0
    ansible.builtin.unarchive:
      src: https://download.visualstudio.microsoft.com/download/pr/895b7e35-b1c2-4d1d-8d7f-f82f4ae70eb7/9470e66ca28443328cbaa36963ff83f8/dotnet-sdk-3.1.416-osx-x64.tar.gz
      dest: /usr/local/share/dotnet
      remote_src: yes

- block:
  - name: "Install dotnet-sdk-6.0.101-osx-x64 : Determine whether SDK is installed"
    shell: dotnet --list-sdks | grep -q ^6\.0\.101\\s
    failed_when: false
    register: dotnet_6_0_101_sdk
    changed_when: false

  - name: "Install dotnet-sdk-6.0.101-osx-x64 : Install SDK"
    when: dotnet_6_0_101_sdk.rc != 0
    ansible.builtin.unarchive:
      src: https://download.visualstudio.microsoft.com/download/pr/4a39aac8-74b7-4366-81cd-4fcce0bd8354/02a581437c26bd88f5afc6ccc81d9637/dotnet-sdk-6.0.101-osx-x64.tar.gz
      dest: /usr/local/share/dotnet
      remote_src: yes

- name: "Add dotnet to path"
  become: true
  copy:
    dest: /etc/paths.d/dotnet
    content: |
      /usr/local/share/dotnet

- name: "Add dotnet-cli-tools to path"
  become: true
  copy:
    dest: /etc/paths.d/dotnet-cli-tools
    content: |
      ~/.dotnet/tools    

- name: "Install JetBrains Rider"
  community.general.homebrew_cask:
    name: rider
    state: present

- name: "Create JetBrains Rider shortcut"
  copy:
    dest: /usr/local/bin/rider
    mode: +x
    content: |
      #!/bin/sh
      open -na "Rider.app" --args "$@"