- name: Install git-gui
  community.general.homebrew:
    name: git-gui
    state: present  

- name: "Install Visual Studio Code"
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
