---
- name: Setup shell prompt
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK: shell prompt"
    path: ~/.zshrc
    create: true
    block: "{{ lookup('file', 'prompt.sh') }}"

- name: Install misc tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - git-gui
    - jq
    - htop

- block: 
  - name: "Install docker : Check existing installation"
    shell: "which docker"
    failed_when: false
    register: which_docker
    changed_when: false

  - name: "Install docker : Install via homebrew cask"
    when: which_docker.rc != 0
    community.general.homebrew_cask:
      name: docker
      state: present  